CREATE TABLE seats(
    id VARCHAR(4) PRIMARY KEY,
    isAvailable BOOLEAN NOT NULL,
    isVIP BOOLEAN NOT NULL,
    isVVIP BOOLEAN NOT NULL,
    owner_id VARCHAR(50)
);

-- TRUNCATE TABLE seats;
INSERT INTO seats(id, isAvailable, isVIP, isVVIP, owner_id) VALUES
('A1', true, true, false, NULL),
('A2', true, true, false, NULL),
('A3', true, true, false, NULL),
('A4', true, true, false, NULL),
('A5', true, true, false, NULL),
('A6', true, true, false, NULL),
('A7', true, true, false, NULL),
('A8', true, true, false, NULL),
('A9', true, true, false, NULL),
('A10', true, true, false, NULL),
('A11', true, true, false, NULL),
('A12', true, true, false, NULL),
('A13', true, true, false, NULL),
('A14', true, true, false, NULL),
('A15', true, true, false, NULL),
('A16', true, true, false, NULL),
('A17', true, true, false, NULL),
('A18', true, true, false, NULL),
('A19', true, true, false, NULL),
('A20', true, true, false, NULL),
('A21', true, true, false, NULL),
('A22', true, true, false, NULL),
('A23', true, true, false, NULL),
('A24', true, true, false, NULL),
('A25', true, true, false, NULL),
('A26', true, true, false, NULL),
('A27', true, true, false, NULL),
('A28', true, true, false, NULL),
('A29', true, true, false, NULL),
('A30', true, true, false, NULL),
('A31', true, true, false, NULL),
('A32', true, true, false, NULL),
('A33', true, true, false, NULL),
('A34', true, true, false, NULL),
('A35', true, true, false, NULL),
('A36', true, true, false, NULL),
('A37', true, true, false, NULL),
('A38', true, true, false, NULL),
('A39', true, true, false, NULL),
('A40', true, true, false, NULL),
('A41', true, true, false, NULL),
('A42', true, true, false, NULL),
('A43', true, true, false, NULL),
('A44', true, true, false, NULL),
('A45', true, true, false, NULL),
('A46', true, true, false, NULL),
('A47', true, true, false, NULL),
('A48', true, true, false, NULL),
('A49', true, true, false, NULL),
('A50', true, true, false, NULL),
('A51', true, true, false, NULL),
('A52', true, true, false, NULL),
('A53', true, true, false, NULL),
('A54', true, true, false, NULL),
('A55', true, true, false, NULL),
('A56', true, true, false, NULL),
('A57', true, true, false, NULL),
('A58', true, true, false, NULL),
('A59', true, true, false, NULL),
('A60', true, true, false, NULL),
('A61', true, true, false, NULL),
('A62', true, true, false, NULL),
('A63', true, true, false, NULL),
('A64', true, true, false, NULL),
('A65', true, true, false, NULL),
('A66', true, true, false, NULL),
('A67', true, true, false, NULL),
('A68', true, true, false, NULL),
('A69', true, true, false, NULL),
('A70', true, true, false, NULL),
('A71', true, true, false, NULL),
('A72', true, true, false, NULL),
('A73', true, true, false, NULL),
('A74', true, true, false, NULL),
('A75', true, true, false, NULL),
('A76', true, true, false, NULL),
('A77', true, true, false, NULL),
('A78', true, true, false, NULL),
('A79', true, true, false, NULL),
('A80', true, true, false, NULL),
('A81', true, true, false, NULL),
('A82', true, true, false, NULL),
('A83', true, true, false, NULL),
('A84', true, true, false, NULL),
('A85', true, true, false, NULL),
('A86', true, true, false, NULL),
('A87', true, true, false, NULL),
('A88', true, true, false, NULL),
('A89', true, true, false, NULL),
('A90', true, true, false, NULL),
('A91', true, true, false, NULL),
('A92', true, true, false, NULL),
('A93', true, true, false, NULL),
('A94', true, true, false, NULL),
('A95', true, true, false, NULL),
('A96', true, true, false, NULL),
('A97', true, true, false, NULL),
('A98', true, true, false, NULL),
('A99', true, true, false, NULL),
('A100', true, true, false, NULL),
('A101', true, true, false, NULL),
('A102', true, true, false, NULL),
('A103', true, true, false, NULL),
('A104', true, true, false, NULL),
('A105', true, true, false, NULL),
('A106', true, true, false, NULL),
('A107', true, true, false, NULL),
('A108', true, true, false, NULL),
('A109', true, true, false, NULL),
('A110', true, true, false, NULL),
('A111', true, true, false, NULL),
('A112', true, true, false, NULL),

('C1', true, false, false, NULL),
('C2', true, false, false, NULL),
('C3', true, false, false, NULL),
('C4', true, false, false, NULL),
('C5', true, false, false, NULL),
('C6', true, false, false, NULL),
('C7', true, false, false, NULL),
('C8', true, false, false, NULL),
('C9', true, false, false, NULL),
('C10', true, false, false, NULL),
('C11', true, false, false, NULL),
('C12', true, false, false, NULL),
('C13', true, false, false, NULL),
('C14', true, false, false, NULL),
('C15', true, false, false, NULL),
('C16', true, false, false, NULL),
('C17', true, false, false, NULL),
('C18', true, false, false, NULL),
('C19', true, false, false, NULL),
('C20', true, false, false, NULL),
('C21', true, false, false, NULL),
('C22', true, false, false, NULL),
('C23', true, false, false, NULL),
('C24', true, false, false, NULL),
('C25', true, false, false, NULL),
('C26', true, false, false, NULL),
('C27', true, false, false, NULL),
('C28', true, false, false, NULL),
('C29', true, false, false, NULL),
('C30', true, false, false, NULL),
('C31', true, false, false, NULL),
('C32', true, false, false, NULL),
('C33', true, false, false, NULL),
('C34', true, false, false, NULL),
('C35', true, false, false, NULL),
('C36', true, false, false, NULL),
('C37', true, false, false, NULL),
('C38', true, false, false, NULL),
('C39', true, false, false, NULL),
('C40', true, false, false, NULL),
('C41', true, false, false, NULL),
('C42', true, false, false, NULL),
('C43', true, false, false, NULL),
('C44', true, false, false, NULL),
('C45', true, false, false, NULL),
('C46', true, false, false, NULL),
('C47', true, false, false, NULL),
('C48', true, false, false, NULL),
('C49', true, false, false, NULL),
('C50', true, false, false, NULL),
('C51', true, false, false, NULL),
('C52', true, false, false, NULL),
('C53', true, false, false, NULL),
('C54', true, false, false, NULL),
('C55', true, false, false, NULL),
('C56', true, false, false, NULL),
('C57', true, false, false, NULL),
('C58', true, false, false, NULL),
('C59', true, false, false, NULL),
('C60', true, false, false, NULL),
('C61', true, false, false, NULL),
('C62', true, false, false, NULL),
('C63', true, false, false, NULL),
('C64', true, false, false, NULL),
('C65', true, false, false, NULL),
('C66', true, false, false, NULL),
('C67', true, false, false, NULL),
('C68', true, false, false, NULL),
('C69', true, false, false, NULL),
('C70', true, false, false, NULL),
('C71', true, false, false, NULL),
('C72', true, false, false, NULL),
('C73', true, false, false, NULL),
('C74', true, false, false, NULL),
('C75', true, false, false, NULL),
('C76', true, false, false, NULL),
('C77', true, false, false, NULL),
('C78', true, false, false, NULL),
('C79', true, false, false, NULL),
('C80', true, false, false, NULL),
('C81', true, false, false, NULL),
('C82', true, false, false, NULL),
('C83', true, false, false, NULL),
('C84', true, false, false, NULL),
('C85', true, false, false, NULL),
('C86', true, false, false, NULL),
('C87', true, false, false, NULL),
('C88', true, false, false, NULL),
('C89', true, false, false, NULL),
('C90', true, false, false, NULL),
('C91', true, false, false, NULL),
('C92', true, false, false, NULL),
('C93', true, false, false, NULL),
('C94', true, false, false, NULL),
('C95', true, false, false, NULL),
('C96', true, false, false, NULL),
('C97', true, false, false, NULL),
('C98', true, false, false, NULL),
('C99', true, false, false, NULL),
('C100', true, false, false, NULL),
('C101', true, false, false, NULL),
('C102', true, false, false, NULL),
('C103', true, false, false, NULL),
('C104', true, false, false, NULL),
('E1', true, false, false, NULL),
('E2', true, false, false, NULL),
('E3', true, false, false, NULL),
('E4', true, false, false, NULL),
('E5', true, false, false, NULL),
('E6', true, false, false, NULL),
('E7', true, false, false, NULL),
('E8', true, false, false, NULL),
('E9', true, false, false, NULL),
('E10', true, false, false, NULL),
('E11', true, false, false, NULL),
('E12', true, false, false, NULL),
('E13', true, false, false, NULL),
('E14', true, false, false, NULL),
('E15', true, false, false, NULL),
('E16', true, false, false, NULL),
('E17', true, false, false, NULL),
('E18', true, false, false, NULL),
('E19', true, false, false, NULL),
('E20', true, false, false, NULL),
('E21', true, false, false, NULL),
('E22', true, false, false, NULL),
('E23', true, false, false, NULL),
('E24', true, false, false, NULL),
('E25', true, false, false, NULL),
('E26', true, false, false, NULL),
('E27', true, false, false, NULL),
('E28', true, false, false, NULL),
('E29', true, false, false, NULL),
('E30', true, false, false, NULL),
('E31', true, false, false, NULL),
('E32', true, false, false, NULL),
('E33', true, false, false, NULL),
('E34', true, false, false, NULL),
('E35', true, false, false, NULL),
('E36', true, false, false, NULL),
('E37', true, false, false, NULL),
('E38', true, false, false, NULL),
('E39', true, false, false, NULL),
('E40', true, false, false, NULL),
('E41', true, false, false, NULL),
('E42', true, false, false, NULL),
('E43', true, false, false, NULL),
('E44', true, false, false, NULL),
('E45', true, false, false, NULL),
('E46', true, false, false, NULL),
('E47', true, false, false, NULL),
('E48', true, false, false, NULL),
('E49', true, false, false, NULL),
('E50', true, false, false, NULL),
('E51', true, false, false, NULL),
('E52', true, false, false, NULL),
('E53', true, false, false, NULL),
('E54', true, false, false, NULL),
('E55', true, false, false, NULL),
('E56', true, false, false, NULL),
('E57', true, false, false, NULL),
('E58', true, false, false, NULL),
('E59', true, false, false, NULL),
('E60', true, false, false, NULL),
('E61', true, false, false, NULL),
('E62', true, false, false, NULL),
('E63', true, false, false, NULL),
('E64', true, false, false, NULL),
('E65', true, false, false, NULL),
('E66', true, false, false, NULL),
('E67', true, false, false, NULL),
('E68', true, false, false, NULL),
('E69', true, false, false, NULL),
('E70', true, false, false, NULL),
('E71', true, false, false, NULL),
('E72', true, false, false, NULL),
('E73', true, false, false, NULL),
('E74', true, false, false, NULL),
('E75', true, false, false, NULL),
('E76', true, false, false, NULL),
('E77', true, false, false, NULL),
('E78', true, false, false, NULL),
('E79', true, false, false, NULL),
('E80', true, false, false, NULL),
('E81', true, false, false, NULL),
('E82', true, false, false, NULL),
('E83', true, false, false, NULL),
('E84', true, false, false, NULL),
('E85', true, false, false, NULL),
('E86', true, false, false, NULL),
('E87', true, false, false, NULL),
('E88', true, false, false, NULL),
('E89', true, false, false, NULL),
('E90', true, false, false, NULL),
('E91', true, false, false, NULL),
('E92', true, false, false, NULL),
('E93', true, false, false, NULL),
('E94', true, false, false, NULL),
('E95', true, false, false, NULL),
('E96', true, false, false, NULL),
('E97', true, false, false, NULL),
('E98', true, false, false, NULL),
('E99', true, false, false, NULL),
('E100', true, false, false, NULL),
('E101', true, false, false, NULL),
('E102', true, false, false, NULL),
('E103', true, false, false, NULL),
('E104', true, false, false, NULL),

('V1', true, false, true, NULL),
('V2', true, false, true, NULL),
('V3', true, false, true, NULL),
('V4', true, false, true, NULL),
('V5', true, false, true, NULL),
('V6', true, false, true, NULL),
('V7', true, false, true, NULL),
('V8', true, false, true, NULL),
('V9', true, false, true, NULL),
('V10', true, false, true, NULL),
('V11', true, false, true, NULL),
('V12', true, false, true, NULL),
('V13', true, false, true, NULL),
('V14', true, false, true, NULL),
('V15', true, false, true, NULL),
('V16', true, false, true, NULL),
('V17', true, false, true, NULL),
('V18', true, false, true, NULL),
('V19', true, false, true, NULL),
('V20', true, false, true, NULL),
('V21', true, false, true, NULL),
('V22', true, false, true, NULL),
('V23', true, false, true, NULL),
('V24', true, false, true, NULL),
('V25', true, false, true, NULL),
('V26', true, false, true, NULL),
('V27', true, false, true, NULL),
('V28', true, false, true, NULL),
('V29', true, false, true, NULL),
('V30', true, false, true, NULL),
('V31', true, false, true, NULL),
('V32', true, false, true, NULL),
('V33', true, false, true, NULL),
('V34', true, false, true, NULL),
('V35', true, false, true, NULL),
('V36', true, false, true, NULL),
('V37', true, false, true, NULL),
('V38', true, false, true, NULL),
('V39', true, false, true, NULL),
('V40', true, false, true, NULL),
('V41', true, false, true, NULL),
('V42', true, false, true, NULL),
('V43', true, false, true, NULL),
('V44', true, false, true, NULL),
('V45', true, false, true, NULL),
('V46', true, false, true, NULL),
('V47', true, false, true, NULL),
('V48', true, false, true, NULL),
('V49', true, false, true, NULL),
('V50', true, false, true, NULL),
('V51', true, false, true, NULL),
('V52', true, false, true, NULL),
('V53', true, false, true, NULL),
('V54', true, false, true, NULL),

('B1', true, false, false, NULL),
('B2', true, false, false, NULL),
('B3', true, false, false, NULL),
('B4', true, false, false, NULL),
('B5', true, false, false, NULL),
('B6', true, false, false, NULL),
('B7', true, false, false, NULL),
('B8', true, false, false, NULL),
('B9', true, false, false, NULL),
('B10', true, false, false, NULL),
('B11', true, false, true, NULL),
('B12', true, false, true, NULL),
('B13', true, false, true, NULL),
('B14', true, false, true, NULL),
('B15', true, false, true, NULL),
('B16', true, false, true, NULL),
('B17', true, false, true, NULL),
('B18', true, false, true, NULL),
('B19', true, false, true, NULL),
('B20', true, false, true, NULL),
('B21', true, false, false, NULL),
('B22', true, false, false, NULL),
('B23', true, false, false, NULL),
('B24', true, false, false, NULL),
('B25', true, false, false, NULL),
('B26', true, false, false, NULL),
('B27', true, false, false, NULL),
('B28', true, false, false, NULL),
('B29', true, false, false, NULL),
('B30', true, false, false, NULL),
('B31', true, false, true, NULL),
('B32', true, false, true, NULL),
('B33', true, false, true, NULL),
('B34', true, false, true, NULL),
('B35', true, false, true, NULL),
('B36', true, false, true, NULL),
('B37', true, false, true, NULL),
('B38', true, false, true, NULL),
('B39', true, false, true, NULL),
('B40', true, false, true, NULL),
('B41', true, false, false, NULL),
('B42', true, false, false, NULL),
('B43', true, false, false, NULL),
('B44', true, false, false, NULL),
('B45', true, false, false, NULL),
('B46', true, false, false, NULL),
('B47', true, false, false, NULL),
('B48', true, false, false, NULL),
('B49', true, false, false, NULL),
('B50', true, false, false, NULL),
('B51', true, false, false, NULL),
('B52', true, false, false, NULL),
('B53', true, false, false, NULL),
('B54', true, false, false, NULL),
('B55', true, false, false, NULL),
('B56', true, false, false, NULL),
('B57', true, false, false, NULL),
('B58', true, false, false, NULL),
('B59', true, false, false, NULL),
('B60', true, false, false, NULL),
('B61', true, false, false, NULL),
('B62', true, false, false, NULL),
('B63', true, false, false, NULL),
('B64', true, false, false, NULL),
('B65', true, false, false, NULL),
('B66', true, false, false, NULL),
('B67', true, false, false, NULL),
('B68', true, false, false, NULL),
('B69', true, false, false, NULL),
('B70', true, false, false, NULL),
('B71', true, false, false, NULL),
('B72', true, false, false, NULL),
('B73', true, false, false, NULL),
('B74', true, false, false, NULL),
('B75', true, false, false, NULL),
('B76', true, false, false, NULL),
('B77', true, false, false, NULL),
('B78', true, false, false, NULL),
('B79', true, false, false, NULL),
('B80', true, false, false, NULL),
('B81', true, false, false, NULL),
('B82', true, false, false, NULL),
('B83', true, false, false, NULL),
('B84', true, false, false, NULL),
('B85', true, false, false, NULL),
('B86', true, false, false, NULL),
('B87', true, false, false, NULL),
('B88', true, false, false, NULL),
('B89', true, false, false, NULL),
('B90', true, false, false, NULL),
('B91', true, false, false, NULL),
('B92', true, false, false, NULL),
('B93', true, false, false, NULL),
('B94', true, false, false, NULL),
('B95', true, false, false, NULL),
('B96', true, false, false, NULL),
('B97', true, false, false, NULL),
('B98', true, false, false, NULL),
('B99', true, false, false, NULL),
('B100', true, false, false, NULL),

('D1', true, false, true, NULL),
('D2', true, false, true, NULL),
('D3', true, false, true, NULL),
('D4', true, false, true, NULL),
('D5', true, false, true, NULL),
('D6', true, false, true, NULL),
('D7', true, false, true, NULL),
('D8', true, false, true, NULL),
('D9', true, false, true, NULL),
('D10', true, false, true, NULL),
('D11', true, false, false, NULL),
('D12', true, false, false, NULL),
('D13', true, false, false, NULL),
('D14', true, false, false, NULL),
('D15', true, false, false, NULL),
('D16', true, false, false, NULL),
('D17', true, false, false, NULL),
('D18', true, false, false, NULL),
('D19', true, false, false, NULL),
('D20', true, false, false, NULL),
('D21', true, false, true, NULL),
('D22', true, false, true, NULL),
('D23', true, false, true, NULL),
('D24', true, false, true, NULL),
('D25', true, false, true, NULL),
('D26', true, false, true, NULL),
('D27', true, false, true, NULL),
('D28', true, false, true, NULL),
('D29', true, false, true, NULL),
('D30', true, false, true, NULL),
('D31', true, false, false, NULL),
('D32', true, false, false, NULL),
('D33', true, false, false, NULL),
('D34', true, false, false, NULL),
('D35', true, false, false, NULL),
('D36', true, false, false, NULL),
('D37', true, false, false, NULL),
('D38', true, false, false, NULL),
('D39', true, false, false, NULL),
('D40', true, false, false, NULL),
('D41', true, false, false, NULL),
('D42', true, false, false, NULL),
('D43', true, false, false, NULL),
('D44', true, false, false, NULL),
('D45', true, false, false, NULL),
('D46', true, false, false, NULL),
('D47', true, false, false, NULL),
('D48', true, false, false, NULL),
('D49', true, false, false, NULL),
('D50', true, false, false, NULL),
('D51', true, false, false, NULL),
('D52', true, false, false, NULL),
('D53', true, false, false, NULL),
('D54', true, false, false, NULL),
('D55', true, false, false, NULL),
('D56', true, false, false, NULL),
('D57', true, false, false, NULL),
('D58', true, false, false, NULL),
('D59', true, false, false, NULL),
('D60', true, false, false, NULL),
('D61', true, false, false, NULL),
('D62', true, false, false, NULL),
('D63', true, false, false, NULL),
('D64', true, false, false, NULL),
('D65', true, false, false, NULL),
('D66', true, false, false, NULL),
('D67', true, false, false, NULL),
('D68', true, false, false, NULL),
('D69', true, false, false, NULL),
('D70', true, false, false, NULL),
('D71', true, false, false, NULL),
('D72', true, false, false, NULL),
('D73', true, false, false, NULL),
('D74', true, false, false, NULL),
('D75', true, false, false, NULL),
('D76', true, false, false, NULL),
('D77', true, false, false, NULL),
('D78', true, false, false, NULL),
('D79', true, false, false, NULL),
('D80', true, false, false, NULL),
('D81', true, false, false, NULL),
('D82', true, false, false, NULL),
('D83', true, false, false, NULL),
('D84', true, false, false, NULL),
('D85', true, false, false, NULL),
('D86', true, false, false, NULL),
('D87', true, false, false, NULL),
('D88', true, false, false, NULL),
('D89', true, false, false, NULL),
('D90', true, false, false, NULL),
('D91', true, false, false, NULL),
('D92', true, false, false, NULL),
('D93', true, false, false, NULL),
('D94', true, false, false, NULL),
('D95', true, false, false, NULL),
('D96', true, false, false, NULL),
('D97', true, false, false, NULL),
('D98', true, false, false, NULL),
('D99', true, false, false, NULL),
('D100', true, false, false, NULL)

DELETE FROM seats WHERE id = 'A1';
DELETE FROM seats WHERE id = 'A2';
DELETE FROM seats WHERE id = 'A3';
DELETE FROM seats WHERE id = 'A4';
DELETE FROM seats WHERE id = 'A6';
DELETE FROM seats WHERE id = 'A7';
DELETE FROM seats WHERE id = 'A8';
DELETE FROM seats WHERE id = 'A9';
DELETE FROM seats WHERE id = 'A10';
DELETE FROM seats WHERE id = 'A11';
DELETE FROM seats WHERE id = 'A12';
DELETE FROM seats WHERE id = 'A13';
DELETE FROM seats WHERE id = 'A19';
DELETE FROM seats WHERE id = 'A20';
DELETE FROM seats WHERE id = 'A22';
DELETE FROM seats WHERE id = 'A23';
DELETE FROM seats WHERE id = 'A24';
DELETE FROM seats WHERE id = 'A25';
DELETE FROM seats WHERE id = 'A26';

DELETE FROM seats WHERE id = 'B51';
DELETE FROM seats WHERE id = 'B52';
DELETE FROM seats WHERE id = 'B53';
DELETE FROM seats WHERE id = 'B54';
DELETE FROM seats WHERE id = 'B55';
DELETE FROM seats WHERE id = 'B56';
DELETE FROM seats WHERE id = 'B57';
DELETE FROM seats WHERE id = 'B58';
DELETE FROM seats WHERE id = 'B59';
DELETE FROM seats WHERE id = 'B60';
DELETE FROM seats WHERE id = 'B71';
DELETE FROM seats WHERE id = 'B72';
DELETE FROM seats WHERE id = 'B76';
DELETE FROM seats WHERE id = 'B77';
DELETE FROM seats WHERE id = 'B78';
DELETE FROM seats WHERE id = 'B79';
DELETE FROM seats WHERE id = 'B80';

DELETE FROM seats WHERE id = 'D41';
DELETE FROM seats WHERE id = 'D42';
DELETE FROM seats WHERE id = 'D43';
DELETE FROM seats WHERE id = 'D44';
DELETE FROM seats WHERE id = 'D45';
DELETE FROM seats WHERE id = 'D46';
DELETE FROM seats WHERE id = 'D47';
DELETE FROM seats WHERE id = 'D48';
DELETE FROM seats WHERE id = 'D49';
DELETE FROM seats WHERE id = 'D50';
DELETE FROM seats WHERE id = 'D61';
DELETE FROM seats WHERE id = 'D62';
DELETE FROM seats WHERE id = 'D63';
DELETE FROM seats WHERE id = 'D64';
DELETE FROM seats WHERE id = 'D65';
DELETE FROM seats WHERE id = 'D66';

-- DROP TABLE seats;

CREATE TABLE users (
    id VARCHAR(50) PRIMARY KEY,
    owned_seat VARCHAR(3)
);

-- TRUNCATE TABLE users;