-- CREATE TABLE seats(
--     id VARCHAR(4) PRIMARY KEY,
--     isAvailable BOOLEAN NOT NULL,
--     isVIP BOOLEAN NOT NULL,
--     isVVIP BOOLEAN NOT NULL,
--     owner_id VARCHAR(50)
-- );

INSERT INTO seats(id, isAvailable, isVIP, isVVIP, owner_id) VALUES
('A2', true, false, false, NULL),
('A3', true, false, false, NULL),
('A4', true, false, false, NULL),
('A5', true, false, false, NULL),
('A6', true, false, false, NULL),
('A7', true, false, false, NULL),
('A8', true, false, false, NULL),
('A9', true, false, false, NULL),
('A10', true, false, false, NULL),
('A11', true, false, false, NULL),
('A12', true, false, false, NULL),
('A13', true, false, false, NULL),
('A14', true, false, false, NULL),
('A15', true, false, false, NULL),
('A16', true, false, false, NULL),
('A17', true, false, false, NULL),
('A18', true, false, false, NULL),
('A19', true, false, false, NULL),
('A20', true, false, false, NULL),
('A21', true, false, false, NULL),
('A22', true, false, false, NULL),
('A23', true, false, false, NULL),
('A24', true, false, false, NULL),
('A25', true, false, false, NULL),
('A26', true, false, false, NULL),
('A27', true, false, false, NULL),
('A28', true, false, false, NULL),
('A29', true, false, false, NULL),
('A30', true, false, false, NULL),
('A31', true, false, false, NULL),
('A32', true, false, false, NULL),
('A33', true, false, false, NULL),
('A34', true, false, false, NULL),
('A35', true, false, false, NULL),
('A36', true, false, false, NULL),
('A37', true, false, false, NULL),
('A38', true, false, false, NULL),
('A39', true, false, false, NULL),
('A40', true, false, false, NULL),
('A41', true, false, false, NULL),
('A42', true, false, false, NULL),
('A43', true, false, false, NULL),
('A44', true, false, false, NULL),
('A45', true, false, false, NULL),
('A46', true, false, false, NULL),
('A47', true, false, false, NULL),
('A48', true, false, false, NULL),
('A49', true, false, false, NULL),
('A50', true, false, false, NULL),
('A51', true, false, false, NULL),
('A52', true, false, false, NULL),
('A53', true, false, false, NULL),
('A54', true, false, false, NULL),
('A55', true, false, false, NULL),
('A56', true, false, false, NULL),
('A57', true, false, false, NULL),
('A58', true, false, false, NULL),
('A59', true, false, false, NULL),
('A60', true, false, false, NULL),
('A61', true, false, false, NULL),
('A62', true, false, false, NULL),
('A63', true, false, false, NULL),
('A64', true, false, false, NULL),
('A65', true, false, false, NULL),
('A66', true, false, false, NULL),
('A67', true, false, false, NULL),
('A68', true, false, false, NULL),
('A69', true, false, false, NULL),
('A70', true, false, false, NULL),
('A71', true, false, false, NULL),
('A72', true, false, false, NULL),
('A73', true, false, false, NULL),
('A74', true, false, false, NULL),
('A75', true, false, false, NULL),
('A76', true, false, false, NULL),
('A77', true, false, false, NULL),
('A78', true, false, false, NULL),
('A79', true, false, false, NULL),
('A80', true, false, false, NULL),
('A81', true, false, false, NULL),
('A82', true, false, false, NULL),
('A83', true, false, false, NULL),
('A84', true, false, false, NULL),
('A85', true, false, false, NULL),
('A86', true, false, false, NULL),
('A87', true, false, false, NULL),
('A88', true, false, false, NULL),
('A89', true, false, false, NULL),
('A90', true, false, false, NULL),
('A91', true, false, false, NULL),
('A92', true, false, false, NULL),
('A93', true, false, false, NULL),
('A94', true, false, false, NULL),
('A95', true, false, false, NULL),
('A96', true, false, false, NULL),
('A97', true, false, false, NULL),
('A98', true, false, false, NULL),
('A99', true, false, false, NULL),
('A100', true, false, false, NULL),
('A101', true, false, false, NULL),
('A102', true, false, false, NULL),
('A103', true, false, false, NULL),
('A104', true, false, false, NULL),
('A105', true, false, false, NULL),
('A106', true, false, false, NULL),
('A107', true, false, false, NULL),
('A108', true, false, false, NULL),
('A109', true, false, false, NULL),
('A110', true, false, false, NULL),
('A111', true, false, false, NULL),
('A112', true, false, false, NULL)

-- UPDATE seats SET isOrder = false WHERE id = 'A2';
-- UPDATE seats SET isAvailable = false WHERE id = 'A9';
-- UPDATE seats SET isOrder = true WHERE id = 'A5';
-- DELETE FROM seats WHERE id = 'A10';

-- DROP TABLE seats;

-- CREATE TABLE users (
--     id VARCHAR(50) PRIMARY KEY,
--     owned_seat VARCHAR(3)
-- );

-- DROP TABLE users;
-- ALTER TABLE seats
-- DROP COLUMN isOrder;

-- TRUNCATE TABLE users;
-- TRUNCATE TABLE seats;